blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/nabeelbaghoor/screen-sharing-touch-bar/security/advisories/new
    about: Please report security problems privately.
